name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.IP_VPS }} "
            git config --global safe.directory '*' ;
            cd /var/www/html/gen-s-backend ;
            if [ ! -d .git ]; then echo 'Project belum ada' && git clone https://oauth2:'${{ secrets.CLONE_TOKEN }}'@github.com/ardhanurfan/gen-s-backend.git .; fi ;
            git pull origin master ;
            if [ -f .env ]; then rm .env; fi ;
            echo '${{ vars.FILE_ENV }}' >> .env ;
            echo 'Run Composer...' ;
            export COMPOSER_ALLOW_SUPERUSER=1 ;
            composer update ;
            composer install ;
            # php artisan migrate ;
            # php artisan key:generate ;
            # npm run dev
            # chmod -R 777 storage ;
            # systemctl restart nginx ;
            echo 'Deployment completed.'
          "
